# Pipeline Logstash pour l'Atelier 3

input {
  beats {
    port => 5044
  }
  http {
    port => 8080
  }
}

filter {
  # Ajoute ici tes transformations (grok, mutate, date, etc.)
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "elasticpassword"
    index => "bd516-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}